language: node_js

git:
  depth: false
  quiet: true

node_js:
  - "stable"

cache: yarn

script:
  - yarn lint:prettier
  - echo "No tests for now"
  - yarn storybook:build
  - yarn build

# only build commits/PRs targeted to the master branch
# this avoids duplicate builds for push + PR
branches:
  only:
    - master

before_deploy:
  - yarn release

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./dist
  on:
    branch: master
