language: node_js

git:
  depth: false
  quiet: true

node_js:
  - "stable"

cache: yarn

stages:
  - lint
  - test
  - build
  - name: deploy
    if: branch = "master" AND type = push AND fork = false

jobs:
  include:
    - stage: lint
      script: yarn lint:prettier
    - stage: test
      script: echo "No tests for now"
    - stage: build
      script: yarn build
    - stage: deploy
      script: yarn release

# only build commits/PRs targeted to the master branch
# this avoids duplicate builds for push + PR
branches:
  only:
    - master
