name: Release

on:
  push:
    branches:
      - master

jobs:
  deploy-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --silent
        env:
          HUSKY_SKIP_INSTALL: true
      - name: Release
        run: |
          yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
